config/routes.rb
Rails.application.routes.draw do
  post 'increment', to: 'counter#increment'
  post 'decrement', to: 'counter#decrement'
  root "counter#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/counter_controller.rb
class CounterController < ApplicationController
  before_action :counter

  def show
  end

  def increment
    counter.increment
    # http_stream_counter
    websockets_stream_counter
  end

  def decrement
    counter.decrement
    # http_stream_counter
    websockets_stream_counter
  end

  private 

  def counter
    @counter ||= Kredis.counter 'mycounter'
  end

  def http_stream_counter
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('counter', html: counter.value)
      end
    end
  end

  def websockets_stream_counter
    Turbo::StreamsChannel.broadcast_update_to('counter_stream', target: 'counter', html: counter.value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/counter/show.html.erb
<%= turbo_stream_from 'counter_stream' %>

<%= button_to '+', increment_path %>

<div id='counter'>
  <%= @counter.value %>
</div>
<%= button_to '-', decrement_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SrKredisCounter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>